name: roshub-ble-serial-server
version: 0.1
summary: ble device service
description: ble device service
base: core18
confinement: strict

apps:
  ble-serial-server:
    command: bleSerialServer

parts:
  ble-serial-server:
    plugin: qmake
    source: src/
    build-packages:
      - qtbase5-dev
      - qtconnectivity5-dev
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5gui5
      - libqt5bluetooth5
    #after: [qt5conf] # A wiki part